Migrate to null-safety
thosakwe/shell pull request #4
Opened 2021-08-14 21:47 UTC by JellyO1

2021-08-14 21:50 UTC, thosakwe commented
Hi, thanks for the PR. It's been a long time since I made this package. Besides null safety, have you run into any other issues with it? Feel free to open a bug report if so.

I should have some time to review this later today.

2021-08-16 11:37 UTC, JellyO1 commented
It seems to be working fine, haven't found anything.

2021-08-16 12:41 UTC, JellyO1 commented
This should also fix issue #3

2021-08-18 12:16 UTC, juliansteenbakker commented
Looking good! Can someone merge this?

2021-08-20 01:01 UTC, thosakwe requested changes
Thank you!!!

2021-08-20 01:01 UTC, thosakwe commented on lib/src/shell.dart
> +  Future<ProcessResult> run(String executable, Iterable<String>? arguments) {
Can you change this to `{Iterable<String> arguments}`?

2021-08-20 01:01 UTC, thosakwe commented on lib/src/shell.dart
> +      String executable, Iterable<String>? arguments) async {
Same here

2021-08-24 02:26 UTC, thosakwe approved these changes

2021-08-24 02:26 UTC, merged

2021-08-24 02:28 UTC, thosakwe commented
Thanks! https://pub.dev/packages/shell/versions/2.0.0